---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: internal-services
    app.kubernetes.io/part-of: internal-services
    app.kubernetes.io/managed-by: kustomize
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: stonesoup-int-srvc
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: damoreno
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: jbieren
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: lmendes
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: shebert
