apiVersion: appstudio.redhat.com/v1alpha1
kind: InternalServicesConfig
metadata:
  name: config
  namespace: stonesoup-int-srvc
spec:
  allowList:
  - managed-release-team-tenant
  - release-catalog-managed-e2e-tenant
  debug: true
  volumeClaim:
    name: pipeline
    size: 1Gi
