---
name: Linters
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ['main']
    types: ['opened', 'reopened', 'synchronize']
  workflow_dispatch:
env:
  TKN_CLI_VERSION: 0.30.1
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run yamllint
        uses: frenck/action-yamllint@v1
        with:
          path: internal-services/catalog/
  tknparse:
    runs-on: ubuntu-latest
    steps:
      - name: checkout files
        uses: actions/checkout@v4
      - name: Install tkn cli
        uses: jerop/tkn@v0.1.0
        with:
          version: v${TKN_CLI_VERSION}
      - name: Get changed files
        uses: tj-actions/changed-files@v41
        id: changed-files
        with:
          files: |
            internal-services/catalog/*.yaml
      - name: Run tkn util
        run: .github/scripts/tkn_check_parse.sh
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REFNAME: ${{ github.ref_name }}
  gitlint:
    name: Run gitlint checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      # Set up Python and create virtual environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Create virtual environment
        run: python3 -m venv venv

      - name: Activate virtual environment and install gitlint
        run: |
          source venv/bin/activate
          pip install gitlint

      - name: Run gitlint check
        run: venv/bin/gitlint --commits origin/${{ github.event.pull_request.base.ref }}..HEAD
  checkton:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
      # Differential Checkton requires full git history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Checkton
        id: checkton
        uses: chmeliik/checkton@v0.2.2 # Migrating to the konflux-ci org
        with:
          fail-on-findings: true
          find-copies-harder: true
