name: Update Image Digest
on:
  schedule:
    - cron: '1 * * * *'
permissions:
  contents: write
  pull-requests: write
jobs:
  run-release-utils:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run update-image-digest script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: "${{ github.actor }}"
          GIT_AUTHOR_EMAIL: "${{ github.actor }}@users.noreply.github.com"
          GIT_COMMITTER_NAME: "${{ github.actor }}"
          GIT_COMMITTER_EMAIL: "${{ github.actor }}@users.noreply.github.com"
        run: |
          .github/scripts/update-image-digest.sh \
            -o "seanconroy2021" \
            -r "app-interface-deployments" \
            -s "main" \
            -t "stable" \
            -f "update-stable-util-image" \
            -i "quay.io/konflux-ci/release-service-utils" \
            -d "false"
